### ISSUE TITLE
Remove dependency to manually create a Tween node for ESCCamera

### ISSUE THREAD

**Issue by dploeger** [godot-escoria/escoria-issues#1]
As a game developer using Escoria I only want to carry out basic tasks when creating required Escoria infrastructure like the game scene.

Currently, attaching the ESCCamera requires creating a Tween node as well.

This should be created by ESCCamera itself without requiring the manual action from the developer.

**Comment by StraToN** [comment]
Was fixed by 00de7fcc4dbe264e1446be1773bc2de045e58b4d. Closing as done.
