### ISSUE TITLE
Error message does not display ESC script filename that caused the error

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#108]
**Please make sure you talk to the community before creating an issue.**

**Describe the bug**
I just received this error from my script :

2022-2-15T174146 (E)    Errors in file Argument type did not match descriptor for command set_state
Argument 1 is of type 1. Expected 4

This error is really cryptic and doesn't help me identify the cause. Which argument is causing the problem (it's argument 1, but it would be handy to have the error message say 'argument 1 = "camera_triggered"' or similar).
My command was "set_state camera_triggered false"
Is argument 1 "camera_triggered", or "false"?

Also, what is a type 1 argument? What is a type 4 argument? These aren't listed in the documentation for set_state, but it would also be good to not have to look up the documentation if it can be provided in the error message. 

There is actually a couple of issues here. 
* Firstly the type "1" isn't helpful to users. I'll add further discussion in the comments below.
* Secondly, you don't know what the argument (in this case, argument "1") actually holds from the error message.
* Thirdly, after reading the source code, [report_errors](https://github.com/godot-escoria/escoria-demo-game/blob/develop/addons/escoria-core/game/core-scripts/log/esc_logger.gd#L200) is supposed to display the filename. Without this, the error message doesn't make sense - i.e. " Errors in file Argument type ..." is incorrect English. [report error](https://github.com/godot-escoria/escoria-demo-game/blob/develop/addons/escoria-core/game/core-scripts/esc/types/esc_command_argument_descriptor.gd#L84) is passing an error message rather than a filename to the command.

**To Reproduce**
Create an ESCItem, attach a script and a CollisionPolygon2D to it.

Associated Escoria code:

```
:trigger_in
set_state camera_triggered true

:trigger_out
set_state camera_triggered false
```

Walk into the associated CollisionPolygon2D.

![image](https://user-images.githubusercontent.com/5151242/154008819-ecf6d797-8e2f-46aa-a118-3a8958f0271b.png)
![image](https://user-images.githubusercontent.com/5151242/154008852-650a46a5-344e-4f10-b542-fdc61ec237d9.png)
![image](https://user-images.githubusercontent.com/5151242/154008931-e8ba9b50-2c6c-47d5-91f7-da68bbb6c999.png)

**Expected behavior**
I suggest an error message like : 

Error in script file. Argument type did not match the type expected by the command set_state.
Argument 1 ("frog") is of type 'string', expected type is 'integer'.

Relevant code : esc_command_argument_descriptor.gd - line 87

**Versions**
* Escoria: Latest demo develop branch
* Godot: 3.4.2

**Comment by balloonpopper** [comment]
In regards to error 1)
Under Godot 2.x you could run a "get_type" command which would pass back the type of the variable passed to it, so you could use that to make the error read more like "Argument 1 is of type int. Expected string" rather than "Argument 1 is of type 1. Expected 4". This isn't supported anymore. The types are specified in the [@Global Scope" for Godot](https://docs.godotengine.org/en/2.1/classes/class_@global%20scope.html#class-global-scope) and from what I can find there's no way to turn the ENUM value back to its name. 

I therefore would propose (and I know this isn't future proof, but without an alternative I think it's still the better option to give users a useful error message) that a list of the current types is provided in esc_command_argument_descriptor.gd and referenced for error messages.

`var godot_type_list = ["TYPE_NIL", "TYPE_BOOL", "TYPE_INT", "TYPE_REAL",  "TYPE_STRING", \
	"TYPE_VECTOR2", "TYPE_RECT2", "TYPE_VECTOR3",  "TYPE_MATRIX32", "TYPE_PLANE", "TYPE_QUAT", \
	"TYPE_AABB", "TYPE_MATRIX3",  "TYPE_TRANSFORM", "TYPE_COLOR", "TYPE_IMAGE", "TYPE_NODE_PATH", \
	"TYPE_RID", "TYPE_OBJECT", "TYPE_INPUT_EVENT", "TYPE_DICTIONARY", "TYPE_ARRAY", \
	"TYPE_RAW_ARRAY", "TYPE_INT_ARRAY", "TYPE_REAL_ARRAY", "TYPE_STRING_ARRAY", \
	"TYPE_VECTOR2_ARRAY", "TYPE_VECTOR3_ARRAY", "TYPE_COLOR_ARRAY", "TYPE_MAX"]

<...>

		if not correct:
			print("SHANE " + godot_type_list[typeof(arguments[index])])
			escoria.logger.report_errors(
				"Argument type did not match descriptor for command \"%s\"" %
						command,
				[
					"Argument %d (\"%s\") is of type %s . Expected %s" % [
						index,
						arguments[index],
						godot_type_list[typeof(arguments[index])],
						PoolStringArray(
							self.types[types_index]
						).join(",")
					]
				]
			)
`

**Comment by balloonpopper** [comment]
Even with the above I'm still not getting quite the output I'd want as an end user. For this esc command (which is wrong)
```
camera_shift 0 -300 5
```
I get the output

Argument type did not match descriptor for command "camera_shift"
Argument 1 ("-300") is of type TYPE_STRING . Expected 2,3

I'm not sure there's a way to get a PoolStringArray to do a lookup of the godot_type_list table. I'd just construct this part of the log message outside the report_errors call and pass it in, but someone else might have a neater solution.

**Comment by dploeger** [comment]
I believe, if you set the logging to debug you will see the esc file in which the error occured. I'm okay with the type ENUM there. Maybe there's a better way in a future version, but for now it's okay. And yes, you can't expect the devs to look up the enum, when this error occurs.

**Comment by balloonpopper** [comment]
@dploeger I've got debug set to TRACE. I tried DEBUG in case that changed anything but it doesn't list the file.
I've looked at the code and by my reading of it, it looks like
- the file is parsed (esc_object_manager.gd - load_esc_file( ) ) and the events are placed in a queue. The filename is not retained at this point.
- totally separately, the queue is parsed by _process in esc_event_manager.gd. 
- When a broken event is encountered an error is flagged without the filename.

The report_errors function (esc_logger.gd) is supposed to display the filename based off the text message (see below), however the naming of the variable (p_path) which I'd expect to contain the filename doesn't sound like a filename variable to me.

```
func report_errors(p_path: String, errors: Array) -> void:
	var text = "Errors in file "+p_path+"\n"
```

In my current case, p_path contains "Argument type did not match descriptor for command camera_shift" rather than a filename.

I can put in a PR for the ENUM, but carrying the filename through for the error message (which I think is critical to debugging) looks like a more substantial change to how everything fits together - adding it to each event on the queue or something?

**Comment by dploeger** [comment]
The Enum PR would be awesome.

The path is something we neglected through the rewrite I have to admit. Also, that path refers to the gd file and not the esc file, so we'll keep this issue to make that more clear while event running.

Thanks for reporting!

**Comment by balloonpopper** [comment]
For tracking the status of this ticket, the Enum PR went in a couple of weeks ago. The remaining issue is that an ESC script error doesn't tell you the filename of the broken ESC script file.
