### ISSUE TITLE
Node types and what they're for / how to use them are not documented

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#115]
**Describe the bug**
Node types like "ESCLocation" are not documented. I can see from experimentation that placing a "ESCLocation" as the child of an "ESCItem" results in the player walking there when you interact with the item, but I can't find this documented anywhere. 

I suggest a "Node Types" section of the documentation that calls out what each node type is for, and how to use it.

**Comment by dploeger** [comment]
@balloonpopper The API-docs aren't enough here? https://docs.escoria-framework.org/en/devel/api/ESCLocation.html

**Comment by balloonpopper** [comment]
2 things here @dploeger  :
* The behavior of adding a location to an item which results in the player walking to the right spot when interacting with the item isn't mentioned anywhere in the API page
* For new user the documentation doesn't mention anything about the API itself. There's no "here's how to use the API" or "when should you use the API instead of ESC scripts" type documentation that I can see. I'm looking at this from the point of view that the user is (potentially) expecting to do everything by making some artwork, adding nodes, and writing scripts - and therefore they'd want to know what the node types are, and how they use them in their scripts.

**Comment by dploeger** [comment]
Makes sense. Thanks
