### ISSUE TITLE
Camera push (and other commands) don't error when limits are set

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#127]
**Please make sure you talk to the community before creating an issue.**

**Describe the bug**
If you try to push the camera to a location (e.g. 1000,1000)  and the camera limits are less than this (e.g. 0,0 to 200,200), the push command will fail silently.

**To Reproduce**
Create a room limit
Use a camera push command in a child script to try and move the camera outside the limit

**Expected behavior**
An error message should appear.

**Versions**
* Escoria: latest dev
* Godot: 3.4.2

**Additional context**

**Comment by dploeger** [comment]
Do you mean a warning in the log or should the game crash with the error message then?

**Comment by balloonpopper** [comment]
I would think a crash. You're asking the camera to go somewhere it's been told it's not allowed.

 I can't see that you can update the limits automatically because the game can't determine how far around the new location it should be allowed to travel.

**Comment by BHSDuncan** [comment]
@balloonpopper can def see it not error out at all w/ `set_camera_pos`.  I'm thinking about adding in additional validation code here, but can you please post an exhaustive list of the commands you're seeing that you've noticed failing silently? It'll save me from having to assume and then double check. Thanks!

**Comment by balloonpopper** [comment]
None spring to mind other than the camera commands @BHSDuncan

**Comment by balloonpopper** [comment]
Actually, this one : https://github.com/godot-escoria/escoria-issues/issues/165
(It would be really handy if this triggered an "unreachable" event you could react to, but that might be outside the scope of what you're looking at)

**Comment by BHSDuncan** [comment]
How do you expect this to behave when multiple camera limits have been set for a room? Just check to see if the new (x, y) position falls within one of the limits?

**Comment by balloonpopper** [comment]
If there's multiple camera limits only one should be active. If the camera_xyz command tells the camera to go outside the active limit then I expect smoke and flames to billow from my computer case at the time the camera command is executed.

**Comment by BHSDuncan** [comment]
Right. I think easiest is just to check the limits when the command is validated right before it runs, and to crash as per your original suggestion. Once this is in place for the camera_* commands, it can be reviewed and modified if necessary.

I'd really like to get this one put to bed since it affects several commands.
