### ISSUE TITLE
Commands without "validate" functions fail without logging an error message

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#132]
**Describe the bug**
For those commands that don't have a "validate" function (e.g. inventory_add), if you fail to pass them the right parameters, they fail without helpful error messages.

**To Reproduce**
1. Add a line saying "inventory_add" to a script (no parameters)
2. Execute the script

![image](https://user-images.githubusercontent.com/5151242/155238184-040f0da3-cbfb-4101-8d2a-a7c17ee79eeb.png)

**Expected behavior**
A log message should say "Required parameters not passed to command [command name] in file [filename]. " or similar.

**Versions**
* Escoria: latest
* Godot: 3.4.2

**Comment by dploeger** [comment]
Oh, yes. That is a mistake in inventory_add, because "null" is used as a default parameter there for whatever reason.

Did you see that only with inventory_add or other commands as well?

**Comment by balloonpopper** [comment]
It's on multiple commands - I'm guessing all of the ones without validate (which looks to be a reasonable number.) As an example, just tried it with camera_shift (as I had the code open)

![image](https://user-images.githubusercontent.com/5151242/155318710-8a70e860-2201-45a5-b67a-f351d0cb6bf4.png)

**Comment by balloonpopper** [comment]
Another example : wait with no parameters
![image](https://user-images.githubusercontent.com/5151242/155318992-dd7bf290-0bcf-490a-833f-deeba8e0e166.png)

**Comment by balloonpopper** [comment]
Unfortunately removing the [null] line (L19) just shifts the problem.
![image](https://user-images.githubusercontent.com/5151242/155413290-ef45e8ba-e917-43fd-991b-21fa7a4f8adf.png)

**Comment by dploeger** [comment]
Meh. Okay. Thanks!

**Comment by BHSDuncan** [comment]
@balloonpopper can you check if PR 569 addresses this?

**Comment by balloonpopper** [comment]
Confirmed fixed under https://github.com/godot-escoria/escoria-demo-game/pull/569
