### ISSUE TITLE
Camera commands use speed parameter when they should use a time parameter 

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#136]
**Is your feature request related to a problem? Please describe.**
Through testing with "camera_set_pos" it's became apparent to me that while I would generally know how many seconds I'd want a camera move to take (as I'd pair it with a "wait" command) I'm not likely to know the pixels per second speed I want a transition to take. 
I'd therefore suggest :  

**Describe the solution you'd like**
- A version of the camera commands that use a time parameter to calculate the length of the tween
- It might also be handy to have a blocking version of the current camera commands for users who want the camera to move at a certain speed, but don't know how long it will take. This would also be more robust if camera positions were moved which might make a previously working tween fail. 

**Describe alternatives you've considered**
I can calculate the time myself with speed = distance / time, but having to calculate the distance manually every time I shift the camera location is not ideal.

**Additional context**

**Comment by dploeger** [comment]
I don't understand you there. The time parameter actually says how long the transition should take. At least that was my understanding. Doesn't it work like that?

And for the blocking suggestion, I had just added that comment to your other issue #135  😄

**Comment by balloonpopper** [comment]
camera_set_target (for example) takes a "speed" value. From experimenting, and looking at the code, the "speed" = number of pixels for the camera to move per second.
From esc_camera.gd
```
func set_target(p_target, p_speed : float = 0.0):
	var speed = p_speed
        <...>
		var time = self.global_position.distance_to(_target) / speed
```
If I want to move the camera focus back to the player in a cutscene for example and want it to take 3 seconds, I can't easily do that as I have to know how far the camera is from the player in pixels, then calculate that as a "speed" for the esc script. If I move the start/end points of the camera movement later (with level changes), I need to recalculate this "speed" if I still want the transition to take the same time.

Fixed speed is good if you want camera movements to scroll smoothly regardless of travel distance, but for cutscenes, scheduling camera movements to work over a set time period would be (at least sometimes) more helpful.

I hope that explains it?

**Comment by dploeger** [comment]
Oh yes, then it really is a bug. This should be the time the whole transition should take based on the docs. Thanks for reporting!
