### ISSUE TITLE
New versions of the camera movement commands with blocking

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#138]
**Is your feature request related to a problem? Please describe.**
This request is to add camera movement commands that block until completed.
See #135 for details of the issue.

**Describe the solution you'd like**
Camera movement commands that block until complete.

**Describe alternatives you've considered**
A change to the code to make long running tweens immediately stop, the camera is moved to the final position, and the new tween starts.

**Additional context**

**Comment by dploeger** [comment]
While this is a valid request, I tend to target it at future to limit scope. wdyt, @StraToN @BHSDuncan ?

**Comment by BHSDuncan** [comment]
I'm in agreement. This should be post-4.0.

**Comment by BHSDuncan** [comment]
Will do for 4.0.
