### ISSUE TITLE
Can't walk to a point within a CollisionPolygon2D

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#147]
**Describe the bug**
If I have a CollisinoPolygon2D that I've assigned to an ESCitem that covers my ESCterrain, I can't "walk" to anywhere in the CollisionPolygon2D

**To Reproduce**
1. Create a walkable terrain
2. Create an ESCitem, with a CollisionPolygon2D
3. Draw the polygon over part of the terrain
4. Play the game and try to walk to the part of the room matching the polygon

**Expected behavior**
I should be able to walk to the polygon if I don't have use/look/etc selected

**Versions**
* Escoria: Latest
* Godot: 3.4.2

**Comment by bolinfest** [comment]
Hmm, this may explain some of the issues I am running into when testing gamepad support in https://github.com/bolinfest/escoria-demo-game/tree/rfc-gamepad-support. For example, room02 has r_platform / Right platform and I can left click to walk to a point within it using the mouse, but not with my current gamepad implementation.

**Comment by bolinfest** [comment]
Perhaps the `_unhandled_input()` methods from `esc_item.gd` and `esc_background.gd` are in conflict?

https://github.com/godot-escoria/escoria-demo-game/blob/cffedb63e19e5d0aa9eeb7eaaa4a8509c3523f33/addons/escoria-core/game/core-scripts/esc_item.gd#L272

https://github.com/godot-escoria/escoria-demo-game/blob/cffedb63e19e5d0aa9eeb7eaaa4a8509c3523f33/addons/escoria-core/game/core-scripts/esc_background.gd#L85

**Comment by bolinfest** [comment]
Ah, I discovered that my issue with gamepad support has to do with a call to `get_tree().set_input_as_handled()` that I was planning to add to `ESCBackground._unhandled_input()` as part of https://github.com/godot-escoria/escoria-demo-game/pull/503, so I think I'll have to remove that. I just took a look at `ESCTerrain` and didn't see any input handling there, but perhaps the calls to `get_tree().set_input_as_handled()` are interfering with your situation, @balloonpopper?

**Comment by bolinfest** [comment]
I believe https://github.com/godot-escoria/escoria-demo-game/pull/516 will fix this specific issue as it manifests in room07, though I believe it is the right thing to do, in general.
