### ISSUE TITLE
Player interactions are accepted while leaving a room

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#161]
**Please make sure you talk to the community before creating an issue.**

**Describe the bug**
If you click on a door to leave the room, once the room transition starts, you can click to make the player walk into the room. They will walk back into the room while the room is fading out.

**To Reproduce**
1. Click on any doorway to leave a room
2. While the room is fading out, make the player walk somewhere else.

**Expected behavior**
Interactions should be stopped until the ready and setup stages of the next room have completed.

**Versions**
* Escoria: Latest
* Godot: 3.4.3

**Comment by dploeger** [comment]
Ah yes. At least the ESCExit should implement disallowing input.

**Comment by BHSDuncan** [comment]
I would submit that it should probably be in the `change_scene` implementation in the room manager since there are ways other than using `ESCExit` to change scenes.

I'll give that a shot and see how it goes, or if we need a different approach.
