### ISSUE TITLE
If the player can't reach an ESCitem's location, no error is displayed and event stops

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#165]
**Describe the bug**
If you have an ESCitem that the player tries to pick up, and the player can't reach the ESCLocation attached to the item, the player will walk to the closest location and the pick up event stops.

This also affects if you want to talk to an NPC and can't reach their associated ESClocation.

Debug reports that they've arrived at the location (but they haven't, they've walked to the wrong spot). Below is all the debug messages from the log.

```
2022-3-5T101723 (I)	Item focused:  	[r9_bottle_middle]
2022-3-5T101726 (I)	Item left clicked 	[r9_bottle_middle, [InputEventMouseButton:7742]]
2022-3-5T101726 (I)	esc_action_manager.do(): item_left_click on item  	[r9_bottle_middle]
2022-3-5T101726 (I)	r9_bottle_middle left-clicked with event  	[[InputEventMouseButton:7742]]
2022-3-5T101726 (D)	player arrived at r9_bottle_middle 	
2022-3-5T101726 (I)	Context arrived: [Object:7745] 	[]
2022-3-5T101726 (I)	Context arrived: [Object:7745] 	[]
2022-3-5T101728 (I)	Item unfocused:  	[r9_bottle_middle]
2022-3-5T101728 (I)	Item unfocused:  	[r9_closet_middle]
```

**To Reproduce**
1. Use room 9 from the demo
2. Move the ESC location attached to one of the bottles to the same location as the bottle
3. Play the level (open all 3 doors then try to take the bottle)

**Expected behavior**
There should be a log message of some sort saying "location unreachable."
Ideally there would be a "can't reach that" event triggered (so the developer can make the avatar say/do something).

**Screenshots**
Room setup
![image](https://user-images.githubusercontent.com/5151242/156855655-58d96bf1-a448-48ec-a829-cdf09bcfce1e.png)

Where the player walks to when you try and take the middle bottle. 
![image](https://user-images.githubusercontent.com/5151242/156856814-7454b542-e6d7-40b7-a929-e2d12bea4f25.png)

**Versions**
* Escoria: Latest
* Godot: 3.4.3

**Additional context**

**Comment by dploeger** [comment]
Yes. I was thinking about this as well.

**Comment by balloonpopper** [comment]
Some initial thoughts on this : 
The "walk_stop" function in esc_movable.gd is where the code prints that it arrived when it didn't.
(link)[https://github.com/godot-escoria/escoria-demo-game/blob/develop/addons/escoria-core/game/core-scripts/behaviors/esc_movable.gd#L290]

Would it be a good idea to add something like the below to the check?
```
	if walk_context.target_object:
		var dist_to_dest = walk_context.target_position.distance_to(parent.get_position())
		if dist_to_dest > [threshold]:
		        do not_arrived action()
```
Points I'm not sure of (assuming this is a good start on a solution) :

* I don't know where you'd store the threshold
* The threshold needs to be zoom-level dependent. (i.e. if your characters are big, 50 pixels might be a good threshold to say you reached the destination, but if you change your characters to 1/10th their normal size, 50 pixels would be a long way away)
* I couldn't see from my poking around how you push an arbitrary event that you could then put an action on
* Like the suggestion I posted for the inventory (#152 ) you would want a default action specified so that you don't have to code a "couldn't reach that" response for every object.
   * Ideally this would be a list that is chosen from randomly
   * There might be reasons you want to be able to override this per room. (Can't think of a good example off the top of my head though)
