### ISSUE TITLE
"Give xyz with" should say "give xyz to"

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#176]
**Describe the bug**
The "with" command when you try to give something to someone should be to instead - i.e. "give xyz to"

**To Reproduce**
1. Try to give something to something

**Expected behavior**
"give xyz to"

**Screenshots**

**Versions**
* Escoria: Latest
* Godot: 

**Additional context**

**Comment by BHSDuncan** [comment]
I swear I put something into ETF that addressed this, and then @StraToN made a similar fix after the game jam...like with an active preposition or something. May need to look into again.

**Comment by balloonpopper** [comment]
Had a bit of a poke around and here's what I found. The preposition comes from esc_tooltip.gd
```
# Preposition: on, with...
var current_prep: String = "with"
```
Nothing changes "current_prep" in the 9 verb repositories so there's currently a single preposition shared between the verbs use (which needs "with") and give (which needs "to")

The verb is set by addons/escoria-ui-keyboard-9verbs/verbs_menu.gd
```
func _on_action_selected(action: String):
	escoria.action_manager.set_current_action(action)
```
and displayed by tooltip_action_target.gd
```
	if !current_action.empty():
		bbcode_text += current_action + "\t"
	if !current_target2.empty():
		bbcode_text += "\t" + current_prep + "\t" + current_target2
```

Thoughts on fixes:
I was thinking :
* Add a preposition variable to verbs_menu.gd (var preposition = "with")
* Add an "if action == give then preposition = "to"" exception statement

But then I'm not sure how you get that preposition out to esc_tooltip from esc_action_manager as I can't see a tooltip member in Escoria when it's running.
Also, I'm not sure how the further changes required would impact the simplemouse UI.
Ideally you probably don't want to hardcode the verbs and prepositions.
And how do you handle translations?

**Comment by BHSDuncan** [comment]
@StraToN I remember me putting in a hack for my game with ETF, but then you putting something into the stock UI, mostly to tackle things like keeping the tooltip consistent when combining items, etc., but I thought you also put something in for the active preposition?

I know the code I put in for my game was something of a hack, so I doubt it'd be very flexible/robust.

**Comment by dploeger** [comment]
This seems like an easy fix for the 9verbs stock UI (switching around the `current_prep` variable depending on `use` or `give` like suggested), but is cosmetics in my eyes, so I'll set it to future.

**Comment by BHSDuncan** [comment]
@dploeger respectfully, I actually disagree. "Give xyz with abc" not only looks wrong, but makes no sense, especially to a native English speaker. I'd like to see this addressed as part of the 4.0.0 release. Happy to discuss further, of course.

**Comment by dploeger** [comment]
WHAT? You disagree? How dare you! 😂

Fair enough. You have a point.

**Comment by BHSDuncan** [comment]
Giving @StraToN a poke on this to see if he remembers what I'm talking about here. :)

**Comment by ArturM** [comment]
Easiest fix will be changing lines 6-7 in escoria-ui-9verbs/tooltip/tooltip_action_target.gd from:

```
if !current_action.empty():
		bbcode_text += current_action + "\t"
```

to  something like:

```
if !current_action.empty():
		bbcode_text += current_action + "\t"
		if current_action == "give":
			current_prep = "to"
```

But if we don't want hardcode actions and prepositinons maybe better solution will be adding dictionary [action -> preposition] to Project settings -> UI and then taking current_prep from this dictionary.

**Comment by BHSDuncan** [comment]
Since this is a UI-specific issue, there's no need to push any code up into the Escoria core.

Your final suggestion is one that I think we actually did last year but it was only temporary for a game jam. Having a dictionary of prepositions to use would probably make the most sense. Localizing those prepositions may also make a good deal of sense, but then I think we'd need to modify the rest of the UI to also be localized.

So, for the sake of getting this done for 4.0, I think a dictionary would suffice with the proper code put into `esc_tooltip.gd`.

Happy to check any PR you submit for this.

**Comment by ArturM** [comment]
Ok, so I try to prepare PR. :)
