### ISSUE TITLE
Ability to swap out the sprites for the player (e.g change the player costume)-

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#185]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to change the player sprites so that I can make them change costume. Presumably the way would be to change the whole ESCRoom's player scene, but 

1) I can't see a supported way to do that.  It appears from the description that set_state might be intended to be used for that - "Can be used to change the appearance of an item or player character." - but I can't see code that matches that description.

2) The change needs to persist between rooms so needs to be a global rather than per-room setting.

**Describe the solution you'd like**
An easy way to set the sprites for the player. Ideally this solution would also be usable for ESCitems so that I don't need separate items for say a light that's on and a light that's off. 

**Describe alternatives you've considered**
None

**Additional context**

**Comment by dploeger** [comment]
This is already possible using `set_animations` which allows you to swap the resource used for the `animations` parameter of an ESCCharacter. That way you can set different animations based on the used animation player. (E.g. one `walk_left` and one `walk_left_fedorahat`)

Maybe this should be better documented then?

**Comment by balloonpopper** [comment]
If you have a quick few steps for the recommended way to do it @dploeger that would be good to hear. I looked at the current example with set_animations (room 15) and it doesn't include changing the graphics - (mark_animations_weird.tres)[https://github.com/godot-escoria/escoria-demo-game/blob/develop/game/characters/mark/mark_animations_weird.tres] has no reference to the spritesheet needed by the 'set_animations' command.
Once I've got it figured out I'll do a new version of room 15 and update the step-by-step guide.

**Comment by dploeger** [comment]
You can check out the start of the first scene of Safehouse where I switch between an animation with a suitcase and without: https://gitlab.com/d1314/safehouse/safehouse-game/-/blob/main/rooms/bedroom/bedroom.esc

You just change the animation name in the animation resource. Both animations need to be in the same animation player/AnimatedSprite.

**Comment by balloonpopper** [comment]
And how did you make the tres file in the first place? I tried making a new animation resource (based off the room15 example), but the tres file doesn't have any reference to the spritesheet.

**Comment by balloonpopper** [comment]
Oh, hang on, you said both animations need to be in the same AnimatedSprite. That explains that then (though seems to me that could get hard to manage if you have a lot of animations). I'll know more when I have time to play with it tonight, but I think I'd prefer a solution where it wasn't all one big file to make it more manageable.

**Comment by balloonpopper** [comment]
Figured it out now from your help @dploeger. Definately needs documentation.
