### ISSUE TITLE
Cutscene in start_game.esc won't play properly

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#195]
**Describe the bug**
I'm trying to put a "company logo" animation cutscene on the start of the demo and it won't play.

**To Reproduce**
Clone [balloonpopper repo](https://github.com/balloonpopper/escoria-demo-game/tree/intro) if possible and run 

Alternatively
start_game.gd: add change_scene line

```
:init

play_snd res://game/sfx/Game-Menu_Looping.mp3 _music

# Play Escoria logo cutscene
change_scene res://game/rooms/intro/intro_room.tscn false

# Showing main menu with automatic transition DISABLED
show_menu main

:newgame
```

intro.esc
```
:setup
set_state intro_animation_player RESET

:ready
set_state intro_animation_player intro
```

Create a game/rooms/intro/intro_room.tscn scene
Scene structure
![image](https://user-images.githubusercontent.com/5151242/158740116-bd87d0eb-e053-4957-afa4-2dcd65f2618f.png)

Room setup:
![image](https://user-images.githubusercontent.com/5151242/158741262-27e0fd88-2d9b-4b52-8911-8e5d9e7fb856.png)

ESCItem:
![image](https://user-images.githubusercontent.com/5151242/158741356-92135f72-fbc5-4345-97b7-e4edfc76a866.png)

Animation player (child of ESCitem)
![image](https://user-images.githubusercontent.com/5151242/158741428-084e7fe0-f0af-4b16-addb-7efd72c8362a.png)

Animation created 
![image](https://user-images.githubusercontent.com/5151242/158741454-54054e69-cf74-499f-bafe-7875aed3d9bf.png)

------------
Log when running Escoria (i.e. start_game.gd). It looks like the scene is run according to the log, but it is never drawn.
```

2022-3-17T161332 (D)	Event setup started 	
2022-3-17T161332 (D)	Running command set_state with parameters [intro_animation_player, RESET, False] 	
2022-3-17T161332 (D)	State "RESET" set. Matching non-immediate animation executing. 	
2022-3-17T161332 (D)	[set_state] Return code: 0 	
2022-3-17T161332 (D)	Event setup ended with return code 0 	
2022-3-17T161332 (D)	esc_event_manager 	[Popping event ready from background queue _front]
2022-3-17T161332 (D)	Event ready started 	
2022-3-17T161332 (D)	Running command set_state with parameters [intro_animation_player, intro, False] 	
2022-3-17T161332 (D)	State "intro" set. Matching non-immediate animation executing. 	

```
---------------
Also, I don't know how to return control back to start_game.gd. As a result, I moved the menu to my intro scene's script
```
:setup | NO_UI
set_state intro_animation_player RESET

:ready | NO_UI
set_state intro_animation_player intro

show_menu main
```
As set_state isn't blocking, the animation starts and immediately the main menu appears.

So I suspect I might not have the right process for implementing a intro cutscene (before the main menu), as well as there being bugs.
(NO_UI also doesn't work, but that's a separate problem)

**Comment by dploeger** [comment]
You didn't seem to transition in there but disabled automatic transitions. And I think, you can use the `anim_block` command here, because you don't need to save the state of the animation, right?

**Comment by balloonpopper** [comment]
🤦‍♂️ I was looking for "play_anim" not "anim*". I thought I was getting confused as I didn't spot the anim* command, and I went with set_state instead. Thanks @dploeger 

I deliberately didn't want to transition in there. Yes we'd probably want to have a transition, but I'll leave it disabled for now until the other bugs are ironed out.

So the outstanding issues:
* As far as I can see there's no way to pass control back to start_game.gd which means I'd have to put ":new_game" at the end of my cutscene. This seems wrong.
* I get the UI showing up at the end of the cutscene - but this will be fixed once the above issue is resolved.
* The cutscene transitions in anyway - even though I have false set for "change_scene"
* If I run Escoria, it correctly runs my cutscene without the UI. If I run the cutscene level directly, it transitions in with the UI then removes it after ":setup" has completed.
* I get the orange "Escoria" page at the very start before my cutscene which I'd want to swap for the new logo animation.
* NO_UI didn't work under the old way I was doing things. Not sure if that bug is worth following up as I should've been using anim_block instead of set_state.

**Comment by balloonpopper** [comment]
Closed with @straton's help.
