### ISSUE TITLE
Disabling scene transitions in start_game.esc as part of :init does not work

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#198]
**Describe the bug**
This code is in start_game.esc. Escoria ignores the "false" to disable the transition on the "change_scene" command.

```
:init

play_snd res://game/sfx/Game-Menu_Looping.mp3 _music

# Play Escoria logo cutscene
change_scene res://game/rooms/intro/intro_room.tscn false
```

In case it ends up relevant, both ":setup" and ":ready" have "NO_UI" set up in the intro_room scene's esc file.

```
:setup | NO_UI
anim_block intro_animation_player RESET

:ready | NO_UI
anim_block intro_animation_player intro

show_menu main
```

**To Reproduce**
As above

**Expected behavior**
There should be no transition

**Comment by BHSDuncan** [comment]
To be clear: If "curtain" is the transition, you'd expect to see just an immediate cutover in the case above, yeah? And if it was "instant", it should be the same thing?

Can you confirm that this only happens with the `:init` event? Or does it happen in regular rooms, too?

**Comment by balloonpopper** [comment]
Yes, so if "curtain" is the default transition type,  I would expect intro_room.tscn to start with an immediate cutover (the same as if "instant" transition was the default)

I have confirmed that this happens with the ":init" event, but doesn't happen in regular rooms.
I set the default transition to curtain and changed the "push" action on the button in room 3 to
```
change_scene "res://game/rooms/room08/room08.tscn" false
```
When the button is pushed you get an "instant" transition to room 8.
Tested against develop and the current (major) transitions change (branch post-issue-102-issues)
