### ISSUE TITLE
Creating two items with the same global id doesn't cause an error

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#203]
**Describe the bug**
If you create 2 x ESCLocations and give them both the same Global ID, this doesn't cause an error to occur like I'd expect. Instead whichever is configured last is the used one (I'm guessing it overwrites the existing one?)

**To Reproduce**
1. As above

**Expected behavior**
I'd expect an error to be raised.

**Comment by dploeger** [comment]
Hmmm. I thought this would error out when they're both [registered with the object manager here](https://github.com/godot-escoria/escoria-demo-game/blob/develop/addons/escoria-core/game/core-scripts/esc/esc_object_manager.gd#L50).

**Comment by balloonpopper** [comment]
No, force is set to true when the room loads which makes it fail that check.
It's being set to force here :
https://github.com/godot-escoria/escoria-demo-game/blob/develop/addons/escoria-core/game/core-scripts/esc_item.gd#L203

**Comment by dploeger** [comment]
Oh okay.
