### ISSUE TITLE
debug command to support outputting the contents of globals and states

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#205]
**Is your feature request related to a problem? Please describe.**
Debug only prints literal strings from what I can see. 

**Describe the solution you'd like**
I would like it to be able to output the value stored in a global, or the status of a state as well.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by dploeger** [comment]
I'd say, that debug should support template strings for that.
