### ISSUE TITLE
Using info command in escoria script hard crashes the engine

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#219]
**Describe the bug**
I assumed from a quick look at the function that I could call this in Escoria script. Doing so crashes the engine. It's fine if the intention is to use the "debug" function to log at other debug levels (e.g. info), but if that's the intention, having the info command in a script shouldn't crash the engine.
```
info "This is my logging message" 
```

**To Reproduce**
As above

**Expected behavior**
Either the info command should display the text when the game is at info log level and above
or
if you're supposed to use the debug command for all log levels (and info etc is just for internal debugging calls) then having "info [...]" in a script shouldn't crash the engine

**Comment by BHSDuncan** [comment]
I currently see something like:

```
 2022-4-15T154927 (E)	Errors in file Invalid command detected: info
Command implementation not found in any command directory
```

This looks about right, and we currently crash to disk with such a message any time an ESC command isn't found. Are you saying that invalid commands should never crash the engine? This is currently by design, and would require discussion if it's to change.

**Comment by balloonpopper** [comment]
I'll close this call. At the time I wasn't aware if "info" should work like the "debug" command worked (i.e. you should be able to log things at the info level). This has since been clarified, so "info" is indeed an unknown command and fails as such.
