### ISSUE TITLE
Extend Escoria with a plugin

### ISSUE THREAD

**Issue by StraToN** [godot-escoria/escoria-issues#24]
How to create a new plugin to extend Escoria, and share it to the world

**Comment by dploeger** [comment]
That's a rather broad description. We already have those:

* [Creating your own dialog manager](https://docs.escoria-framework.org/en/devel/advanced/create_dialog_manager.html)
* [Creating a custom UI](https://docs.escoria-framework.org/en/devel/advanced/create_ui.html)
* [https://docs.escoria-framework.org/en/devel/advanced/custom_esc_commands.html](Creating custom ESC commands)

Are there any other aspects we should be covering?

**Comment by StraToN** [comment]
I think these pages are sufficient. Let's close this issue then.
