### ISSUE TITLE
Debugging, performance and team working

### ISSUE THREAD

**Issue by StraToN** [godot-escoria/escoria-issues#25]
- Where to check if something doesn't work as intended
- How to debug when Escoria fails in error or warning
- How to optimize
- Bad practices and limitations
- Version control

**Comment by dploeger** [comment]
Hmmm. What should we cover here, that is not covered by the Godot docs?

**Comment by StraToN** [comment]
"How to debug when Escoria fails in error or warning" is a specific part I'd like to explain: almost everything can be accessed in "escoria" object, but I'd like to give directions on how to access it and where to look.

**Comment by StraToN** [comment]
Closed by https://github.com/godot-escoria/escoria-docs/pull/28
