### ISSUE TITLE
ESCItems with TextureRect are ignored when the mouse moves over the TextureRect

### ISSUE THREAD

**Issue by Patlamgoc** [godot-escoria/escoria-issues#255]
Hi, I'm a newbie so I hope I'm reporting a real thing.

In Escoria Step-by-step Guide, ESCItem nodes aren't working as stated in Making The Player Walk Behind Items and Creating An Inventory sections; it is directed to add TextureRect nodes for the walk behind (barrel) and inventory (mug) items but by doing so, CollisionShape2D/Polygon2D areas (where they overlap with the texture images) can't be clicked or interacted when the scene played but changing the TextureRect setting to Mouse>Filter>Ignore or using a Sprite node instead of a TextureRect solved the issue for me and ESCItems worked as stated in the guide. Before that I had monkeyed with z-indexes, area nodes' orders on object trees, and had tried different interaction methods (verbs) in associated ESC script file etc. with no avail, it seemed the problem was irrelevant to all of these.

1. Add an ESCItem node to a new or a room scene.
2. Add TextureRect node to ESCItem and assign an image to texture.
3. Add CollisionShape2D/Polygon2D node to ESCItem.
4. Adjust the collision area as necessary to cover the item's interactable zone.
5. Add some text to Tooltip Name of ESCItem to be able to check later if the item would interact with the mouse cursor or not.
6. If you have added item as a separate scene, instance it in the room scene.
7. Add ESCLocation to ESCItem in the room scene and place its crosshair in the walkable zone just in case (in fact it doesn't matter if you don't, also it isn't mentioned in the guide).
8. Play the room scene and see the collision area of the ESCItem is not clickable or interactable where it overlaps with its texture image. If you use Simple Mouse UI, you see neither you can cycle through the interaction types by right clicking the item nor left clicking does something, even tooltip doesn't show up when hovering over the texture area. Collision area which by any chance doesn't overlap with the ESCItem's texture image's rectangle can be clicked or interacted in a way but it still prevents the item to be used in some means like as an inventory item.

**Expected behavior**
ESCItem nodes should work properly if we follow the Step-by-step Guide.

**Versions**
* Escoria: escoria-game-template-4.0.0-alpha.128
* Assetlibs: Simple Dialogs 4.0.0-alpha.16, Simple Mouse UI 4.0.0-alpha.22
* Godot: v3.4.4-stable_win64, v3.5-beta4_win64

**Additional context**
Related guide pages: 
1. https://docs.escoria-framework.org/en/devel/getting_started/step_by_step/5_adding_items.html#making-the-player-walk-behind-items
2. https://docs.escoria-framework.org/en/devel/getting_started/step_by_step/6_handling_inventory.html#creating-an-inventory-item

Thanks for your time in advance.

**Comment by Patlamgoc** [comment]
Thank you @balloonpopper and your team for a marvellous effort :)

In fact after I reported this, I couldn't make the ESCExit node to work either by following the guide but I overcame them eventually by minor guessing, to cut a long story short, I'll list my changes below.

Last but not least, guide suggests room01, room02 naming at first, hence scene files are created with these names initially but every directive addresses them as 'pub' and 'park' .tscn files afterwards.

I know all above are minor typo issues but can be confusing enough for beginners like me :) I think there's no need to flood the main thread for them so I'm reporting here.

Thanks very much in advance. 

Context: https://docs.escoria-framework.org/en/devel/getting_started/step_by_step/7_room_two.html#configure-the-change-between-rooms

From:
```
> [eq ESC_LAST_SCENE room_park]
   teleport player pub_exit
   # Set player look left
   set_angle player 180
```
To:
```
:setup
> [eq ESC_LAST_SCENE park]
   teleport graham pub_exit
   # Set player look left
   set_angle graham 225
```
From:
```
> [eq ESC_LAST_SCENE pub]
   teleport player park_exit
   # Set player look right
   set_angle player 90
```
To:
```
:setup
> [eq ESC_LAST_SCENE pub]
   teleport graham park_exit
   # Set player look right
   set_angle graham 90
```
From (note the extra backtick) :
```
:exit_scene`
say player "I'm leaving now."
change_scene "res:///rooms/park.tscn"
```
To:
```
:exit_scene
say player "I'm leaving now."
change_scene "res:///rooms/park.tscn"
```

**Comment by balloonpopper** [comment]
Cheers @Patlamgoc . Sorry that you are experiencing these problems - it's vital that the walkthrough is solid for new users. Don't feel that they're small typos, they're important. Please let us know if anything you find - walkthrough issues will be a priority to fix.

If you need help, the help channel on the team discord is also a good place to post. We're a small team but we do our best to help new users and fix any issues. Thanks again!

**Comment by Patlamgoc** [comment]
You are welcome, I'll report whenever it seems necessary, thank you for your time :)

**Comment by balloonpopper** [comment]
@Patlamgoc I've reopened this ticket - I'm putting in a PR for fixing the documentation issues as we speak. This ticket will now be used to track the issue with TextureRect and the mouse.

**Comment by balloonpopper** [comment]
Documentation updates in https://github.com/godot-escoria/escoria-docs/pull/52

**Comment by balloonpopper** [comment]
Further testing - also fails when a colorrect is under the escitem's collisionpolygon. Maybe it's related to all control nodes?

**Comment by balloonpopper** [comment]
On doing further testing and research, this is a known Godot fault.
https://github.com/godotengine/godot/issues/24083
As it's been an open Godot RFC for a few years, the fix will have to be to update any documentation reference :
- change "TextureRect" to "Sprite"
- Update any images showing TextureRect to the sprite icon
- Add a note to the FAQ that says if you use TextureRect or ColoredRect, you have to explicitly change their "Mouse Filter" parameter to "Ignore"

**Comment by Patlamgoc** [comment]
I took a glance at your commit on guide repo but some typos will still be there I'm afraid :)

I think ESC code blocks proposed for ESCExit node still needs a :setup directive at the beginning of them because relevant ESC files are being created for the first time so no :setup code block is already there beforehand to add them.

Also ESCItem type exit's ESC file should be like below, it still needs a graham and a correct path for the scene file :)
```
:exit_scene
say graham "I'm leaving now."
change_scene "res://rooms/park/park.tscn"
```

Thank you very much for your time.

**Comment by Patlamgoc** [comment]
Ok @balloonpopper, I checked once more.

Room scenes immediately begin to crash for ESCExit node if I omit ':setup' directive from ESC files (room_pub.esc and room_park.esc to be exact), room scenes even can't be loaded in first place when played. I'm not sure if it's only for me but when I restore :setup directives, everything works flawlessly again. Perhaps naked verbs in an ESC script is considered ambiguous or some default initialization states have been changed for scripts as code evolves.

Hope this helps :) Thank you again.

**Comment by balloonpopper** [comment]
@Patlamgoc - can you please tell me if you read to add a script to make that work somewhere, or if you were following the pattern from creating ESCItems? You don't use scripts for ESCExit nodes :

https://docs.escoria-framework.org/en/devel/getting_started/step_by_step/7_room_two.html?highlight=escexit#room-exits-in-escoria :
"For exits that don’t require scripts, the [ESCExit](https://docs.escoria-framework.org/en/devel/api/ESCExit.html) node is provided. The only things you will need to configure on the node are the “target_scene” to change to, and optionally, a “switch sound” (the sound to play when changing rooms)."

I've just tested this (re)making a doorway between two of the rooms in the demo. I made a new ESCExit node with a CollisionPolygon and a ESCLocation child. I then changed only the "TargetScene" on the node to point it at the next room's scene.
![image](https://user-images.githubusercontent.com/5151242/165738205-321767fc-0b77-4c36-9d62-756965aec1bd.png)
This ESCExit has no script and worked perfectly for me.

ESCExit's should not have an attached script. Try removing the script and updating the TargetScene parameter and see if that works for you please.

**Comment by Patlamgoc** [comment]
You're correct @balloonpopper, vanilla ESCExit node works without scripts for me too and I've not added any scripts to ESCExit nodes either from the beginning but for the character to appear in the correct location and face appropriate direction on the entered scene (for example in front of the pub door facing left, not the default start location), guide later directs the reader to create and add ESC scripts named room_pub.esc and room_park.esc to ESCRoom nodes obviously and these scripts is crashing the scenes without :setup or :ready directives in place for me.

I hope I'm phrasing the situation correctly :) Thank you for your time.

**Comment by balloonpopper** [comment]
@Patlamgoc. I'm a little confused with what's going on, so let me clarify how it works. If the documentation isn't clear, feel free to suggest changes.
ESCExit's we've covered don't require any scripts.
Ready and Setup events run before the player is allowed to start moving the character. If you wanted logic to start the character in a specific spot (at a doorway for example) then these DO need to be in setup or ready.  An ESCExit (or an ESCItem with "is exit" selected) on room "pub" just tells Escoria to load room "park", but nothing about what to do when "park" is loaded. Anything to do with setup in the new room is configured in the new room, which is why you need to place the configuration in the setup or ready of those rooms. Does that clarify things?

Ah, I just read the documentation and I think I see the problem. It doesn't tell that this code
"> [eq ESC_LAST_SCENE room_park]
   teleport player pub_exit
   # Set player look left
   set_angle player 180"
 needs to go in setup/ready. I'll update that.

**Comment by Patlamgoc** [comment]
Yes, I'm telling the same thing :) ESCExit nodes aren't the problem, ESCExit section of the guide has issues, in fact problematic scripts are this
```
> [eq ESC_LAST_SCENE room_park]
   teleport player pub_exit
   # Set player look left
   set_angle player 180
```
and this
```
> [eq ESC_LAST_SCENE pub]
   teleport player park_exit
   # Set player look right
   set_angle player 90
```
on the guide page. They had typos at first but I saw that your commit has been addressed them properly but these codes need a :setup or :ready directive (at least for me) to work when added to room nodes as a script file.

Hope this helps :) Thank you.
