### ISSUE TITLE
If you press esc while a transition is running, Escoria crashes

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#257]
**Describe the bug**
If you press ESC while the "door opening" sound is closing while leaving room 1, Escoria crashes.

**To Reproduce**
As above
![image](https://user-images.githubusercontent.com/5151242/165506785-cb1d99a1-0b7b-4a3d-9dbc-2f94b6b30ae3.png)

Error in the output window
 2022-04-27T21:12:19 (W)	Warnings in file ESCObjectManager:get_object()
Object with global id _camera in room instance (room2, 4623) not found
 	

**Expected behavior**

**Screenshots**

**Versions**
* Escoria: 
* Godot: 

**Additional context**

**Comment by BHSDuncan** [comment]
@StraToN should we disable pausing during a `change_scene` command?

**Comment by BHSDuncan** [comment]
#161 is similar/related

**Comment by balloonpopper** [comment]
@BHSDuncan from Discord, that was the decision.
![image](https://user-images.githubusercontent.com/5151242/165897955-1c19b642-2587-43df-8a3e-73e9bc33ded7.png)

**Comment by BHSDuncan** [comment]
Got it, but given #161 shouldn't we disallow/ignore all user input during a transition?

**Comment by balloonpopper** [comment]
I would assume so

**Comment by BHSDuncan** [comment]
I'm going to make an executive decision here and see about ignoring all user input during a transition. Hopefully it isn't too much work, but it'll require a good bit of testing.

**Comment by balloonpopper** [comment]
This is broken in the latest PR
Using instant transitions : Start in room 3, use door 2 doorway, press esc
![image](https://user-images.githubusercontent.com/5151242/167397314-07abc0e4-c85a-4bb8-873b-e5f38cf9f749.png)
![image](https://user-images.githubusercontent.com/5151242/167397356-ace407a4-cd47-4a4e-9d2c-25ad632f1f86.png)
Transitions are also very slow. There's an additional ~1 second before they start over what it used to be. Also, if you change transition to curtain, there's a ~1/2 second pause between the transition-out ending and the transition-in starting.
