### ISSUE TITLE
Lots of errors get logged when you use the pen with the paper

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#270]
**Describe the bug**
Lots of errors get logged when you use the pen with the paper

To Reproduce
As above

Expected behavior
Not the above

Versions
Escoria: Latest
Godot: 3.4.4

![image](https://user-images.githubusercontent.com/5151242/169675032-0f9d3138-9bc6-4218-8a93-41433350421c.png)

**Comment by BHSDuncan** [comment]
I'm not seeing any errors at all with the latest version in `develop`. Can you please check to see if this is still an issue and close it if not? Thanks!

**Comment by balloonpopper** [comment]
Fixed after refactor.
