### ISSUE TITLE
Dialogs, translations, speech audio

### ISSUE THREAD

**Issue by StraToN** [godot-escoria/escoria-issues#28]
- How to write dialogs in ESC
- How to link dialog lines to speech and dialogs
- Lip sync?
- Ink?

**Comment by dploeger** [comment]
Dialogs are covered in the ESC reference, but we should flesh it out in its own page a bit more (especially the speech part)

**Comment by dploeger** [comment]
Currently no lip sync or ink support for 4.0.0 planned
