### ISSUE TITLE
Talking head graphics in room 1 missing after refactor

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#286]
**Describe the bug**
Looking at the right painting in room 1 the talking head has gone missing.

**To Reproduce**
As above

**Expected behavior**
There should be a disembodied head floating in the dialogue window.

**Screenshots**
![image](https://user-images.githubusercontent.com/5151242/178187819-b9709d89-ee8b-49fe-85ae-6cc41f3be715.png)

**Versions**
* Escoria: Latest
* Godot: 3.4.4

**Additional context**

**Comment by MatteoPiovanelli-Laser** [comment]
In the commit from July 10 (the big refactor), the setting for `dialog_simple/avatars_path=""` (in project.godot) was set to empty string.
Setting that back to its former value of `res://game/dialog_avatars` causes the avatars to reappear correctly.

**Comment by StraToN** [comment]
Maybe we should log a warning if that pas is not set or incorrect?

**Comment by balloonpopper** [comment]
You might have a game that doesn't use dialog avatars - but having the "say" command show a non-blocking error if the setting isn't valid would be good.
