### ISSUE TITLE
Escoria tutorial game freezes when taken a step.

### ISSUE THREAD

**Issue by pursickle** [godot-escoria/escoria-issues#288]
Following escoria docs step-by-step guide and get to the testing point the main menu works, but as you start a new game you can only move once and then the game freezes (mouse does not freeze though). Godot debugger has nothing to say about it.

P.S. After rebooting it worked.

**Comment by balloonpopper** [comment]
@pursickle - if you update your codebase to the latest in the dev branch on Github (not what's in the Godot asset store) you now get a message telling you to restart after enabling the Escoria core plugin. There's some initial strangeness with plugins in Godot that we can't work around unfortunately, but things sort themselves out after a restart of the project. 

I'll leave this ticket open for now in case you'd like to comment, but will close it in a while if you're happy with the response.

**Comment by balloonpopper** [comment]
Closed due to no reply
