### ISSUE TITLE
Room 12 left door has broken

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#296]
**Describe the bug**
One of the recent changes has broken room 12. When you try to use the left door the debug says that the destination point couldn't be reached so no action will run. A quick test of moving the associated ESClocation into the middle of the walkable floor results in the same problem - he walks to the ESClocation but doesn't do anything.

**To Reproduce**
Run room 12 directly
Try to use the left door

**Expected behavior**
Room 11 should load

**Screenshots**

**Versions**
* Escoria: Latest
* Godot: 3.5

**Additional context**

**Comment by BHSDuncan** [comment]
This is well and truly strange. **This only happens with Godot 3.5!**

`if not player_global_pos.is_equal_approx(destination_position):`

Given `player_global_pos` = (37.451111, 392.044891) and `destination_position` = (37.452099, 392.045013), the above `is_equal_approx` actually returns `false`! How weird is that?

But in Godot 3.4.4, the check seems to pass.

I'll bring it up on the Godot Discord.

**Comment by BHSDuncan** [comment]
It looks like the soon-to-be-deprecated `Navigation2D` class has changed something with its `get_simple_path()` method. :( I don't know how we can easily fix this unless we hack something in...
