### ISSUE TITLE
Rooms, navigation, shading and complex setups

### ISSUE THREAD

**Issue by StraToN** [godot-escoria/escoria-issues#30]
- [x] Details of all parameters available in ESCRoom
- [x] What children nodes are needed: ESCBackground, Navigation...
- [x] How to setup the room to add depth map, light map, front elements (that character can walk behind)
- [ ] Parallax, scrolling in large scenes (vertical and horizontal)

**Comment by dploeger** [comment]
Would you say that everything aside from parallax scrolling is covered in the step by step guide now?

**Comment by StraToN** [comment]
Indeed, a good part of this issue is already covered. I edited the list above.
