### ISSUE TITLE
Running/Loading/Saving Game Produces `skip_dialogs` Error When Settings File Doesn't Exist

### ISSUE THREAD

**Issue by BHSDuncan** [godot-escoria/escoria-issues#312]
**Describe the bug**
(This comes from user `jimbobrjames` in Discord.)
Running Escoria w/ Simple Mouse UI produces this error:

![image](https://user-images.githubusercontent.com/3834773/197638736-686bd097-ba47-4629-8542-65ba9ade0920.png)

**To Reproduce**
1. Clone and select Simple Mouse UI as addon UI.
2. Run the game.
3. Note the error.

**Expected behavior**
That the setting is properly registered and no error is produced.

**Screenshots**
See above.

**Versions**
* Escoria: Oct. 2022
* Godot: 3.5/3.5.1

**Comment by StraToN** [comment]
Taking care of that one for 4.0. Thanks

**Comment by BHSDuncan** [comment]
More accurate info/debugging, care of a stack trace from another user `FunniBunni`:

![image](https://user-images.githubusercontent.com/3834773/199531249-e03ce6d1-a1cd-4594-9812-2a3268e11b26.png)

"This relates to a bug that was reported earlier (actually in this channel). it'll be addressed in due course, but it looks to be an issue when starting up and the Escoria settings file doesn't exist. it then tries to create it, including saving all of the settings (once created, the block of offending code isn't run again unless you save/load a game, i believe). 

One of those settings, skip_dialogs, for some reason, is missing from a plugin initialization and that needs to be sorted out."

**Comment by balloonpopper** [comment]
Being fixed under https://github.com/godot-escoria/escoria-demo-game/pull/640

**Comment by BHSDuncan** [comment]
@balloonpopper can you do me a favour and check to see if this is still an issue now that 640 is merged? Thanks!

**Comment by balloonpopper** [comment]
Retested and this is now resolved in the develop branch.
![image](https://user-images.githubusercontent.com/5151242/205470285-2d7aa015-cd5b-4c74-bf9b-2e8795a28bf1.png)

**Comment by balloonpopper** [comment]
Investigating with https://github.com/godot-escoria/escoria-issues/issues/111
