### ISSUE TITLE
Unusable area with simplemouse

### ISSUE THREAD

**Issue by balloonpopper** [godot-escoria/escoria-issues#336]
**Please make sure you talk to the community before creating an issue.**

**Describe the bug**
In the attached picture, the area in the pink box cannot be used. Even though the UI is not on this area, Escoria acts like it is and does not recognise clicks here.
![image](https://user-images.githubusercontent.com/5151242/205627084-c48041b4-9ebe-4398-a3c8-4812b9d9a43c.png)

**To Reproduce**
Turn on simplemouse. Try and walk down the bottom of the screen.

**Expected behavior**
This should be usable area for the player

**Versions**
* Escoria: Latest
* Godot: 3.5

**Additional context**

**Comment by BHSDuncan** [comment]
Yeah...SimpleUI needs a lot of catch-up work in general. Thanks for making note of the particular issues. I think we'll address these as much as possible once we get closer to the 4.0 release, and I do think a lot of these should be fixed for the 4.0 release itself.

**Comment by Reptapog** [comment]
Jumping in here because I was just dealing with this but it's definitely a matter of the ui Control node sitting on top of everything. It also effects any interactable items/areas placed in that region. There's definitely cleaner and less hacky ways to do it but I just positioned the ui node out of the viewport and offset its children accordingly

**Comment by balloonpopper** [comment]
Changing the mouse pass-through setting to "ignore" on the HBox,VBox, Spacer and UI nodes in game.tscn fixes it, however it showed me another bug.
If you right click off the background, the mouse cursor won't change. The immediate fix is to resize all backgrounds to be at least 1200x900 (the game resolution). This also exposed another problem in that you can't currently give the completed application form to the worker in room 6. I need to look at that later.
