### ISSUE TITLE
Newly-set Animation Resource Doesn't Survive Room Change

### ISSUE THREAD

**Issue by BHSDuncan** [godot-escoria/escoria-issues#63]
**Please make sure you talk to the community before creating an issue.**

**Describe the bug**
The animation resource set by using `set_animations` in ESC is changed back to the original animation resource for the character once the character walks into a new room.

**To Reproduce**
1. Create a game with two rooms, a character and two animation resources.
2. Set one animation resource as the default.
3. Call `set_animations` in the first room and pass in the second animation resource.
4. Change the scene to the second room.
5. Note that the animation resource has been changed back to the first one.

**Expected behavior**
Animation resource changes should be permanent until `set_animations` is called again.

**Versions**
* Escoria: 4.0.0-alpha.15
* Godot: 3.3.4

**Comment by dploeger** [comment]
Hm, I think we need a global cache for this somehow that records which animation resource which character was set to, because we destroy the player node and reinstate it when changing the scene.

This cache should be stored in save games. @StraToN Maybe saving it as a dictionary in a reserved global makes sense?

**Comment by StraToN** [comment]
> Hm, I think we need a global cache for this somehow that records which animation resource which character was set to, because we destroy the player node and reinstate it when changing the scene.
> 
> This cache should be stored in save games. @StraToN Maybe saving it as a dictionary in a reserved global makes sense?

This, and/or avoid reloading the player maybe, by keeping a reference in the `escoria.main` object. I don't recall why the player is reloaded in each room.

**Comment by BHSDuncan** [comment]
Could it be because you require a "player scene" in each `ESCRoom`, and so could potentially have a different player scene for each room?

**Comment by StraToN** [comment]
Maybe this could be set by ESC instead, with a command such as `set_player_scene` for example. That would prepare the terrain for future player switch.

**Comment by StraToN** [comment]
Closed by https://github.com/godot-escoria/escoria-demo-game/pull/459
