### ISSUE TITLE
Non-existent Signals/Connections

### ISSUE THREAD

**Issue by BHSDuncan** [godot-escoria/escoria-issues#64]
**Please make sure you talk to the community before creating an issue.**

**Describe the bug**
Escoria is producing errors (but not crashing) in the following locations:

- `inventory_ui.gd`: The disconnection to "input_event" is saying that that there is no such connection to disconnect.
- `esc_player.gd`: There is a small handful of signals being disconnected in `remove_item_by_id`, of which several are apparently for signals that don't exist. Maybe they changed names or were removed?

**To Reproduce**
1. Create a game with inventory items.
2. Add and then remove any inventory item.

**Expected behavior**
Errors shouldn't be thrown.

**Versions**
* Escoria: 4.0.0-alpha.15
* Godot: 3.3.4

**Comment by StraToN** [comment]
I remarked we connect many signals that are meant to be removed after being received once. Godot allows us to create connections that are automatically removed after having been received.

**Comment by BHSDuncan** [comment]
Ok, but can anything be done for the errors showing up when running?

**Comment by StraToN** [comment]
@BHSDuncan yes, definitely. Actually I removed some of these errors already, but I know there are some left. We definitely want to have them gone.

**Comment by dploeger** [comment]
@BHSDuncan What did you mean with the "disconnects to input_event" in inventory_ui.gd I can't find any of those.

**Comment by dploeger** [comment]
Ohh. I think you mixed up the files, right? The input_event thing is for esc_player.gd

**Comment by dploeger** [comment]
THAT was fixed in godot-escoria/escoria-demo-game#465

**Comment by dploeger** [comment]
Added a PR to fix the remaining thing.

There still might be errors or warnings somewhere, but let's close this issue after merging the PR at least.
