### ISSUE TITLE
Make Disappearing Time for Lines of Dialog Dynamic

### ISSUE THREAD

**Issue by BHSDuncan** [godot-escoria/escoria-issues#82]
**Please make sure you talk to the community before creating an issue.**

**Describe the solution you'd like**
Currently, all spoken dialog text disappears after the same amount of time. This can make it difficult for reading as it may feel like shorter lines wait too long before disappearing or longer lines don't wait enough time before disappearing.

Perhaps an additional argument to the `say` command could inform the dialog manager how long to wait.

**Comment by elvisish** [comment]
The text should probably have a time scale, where it's multiplied by the amount of words or characters are in a line.

**Comment by dploeger** [comment]
Yes. I was planning to use a calculation by common reading speed that I've used over at EgoVenture as well.
