### ISSUE TITLE
Tokenize String Literals

### ISSUE THREAD

**Issue by BHSDuncan** [godot-escoria/escoria-issues#90]
**Please make sure you talk to the community before creating an issue.**

**Is your feature request related to a problem? Please describe.**
Currently, string literals are strewn about the code, e.g. for parsing/compiling ESC commands. Should the value of these literals need to change, changing each instance will be error prone and time-consuming (can't always use `sed`).

**Describe the solution you'd like**
For each "magic string" encountered, decide on the best place to locate a constant to house the literal and use/reference wherever needed in code.

**Comment by BHSDuncan** [comment]
[escoria-literals.ods](https://github.com/godot-escoria/escoria-issues/files/7739847/escoria-literals.ods)
Spreadsheet containing those literals that have been tracked down after a first pass. In OpenOffice Calc format.

**Comment by dploeger** [comment]
[escoria-literals.ods](https://github.com/godot-escoria/escoria-issues/files/7757542/escoria-literals.ods)
I've added my comments to the string literals sheet. All checkmarks just mean "go ahead, do it" ;-) The entries in the other sheet already went into another issue, right?

@StraToN would you kindly go over this as well?

**Comment by BHSDuncan** [comment]
> The entries in the other sheet already went into another issue, right?

Correct. 93 and 94 I believe.

Will wait for @StraToN 's feedback!

**Comment by StraToN** [comment]
Ok I edited the file to add my own commands but to make it short and easy I agree with @dploeger on all lines. Just a few additional remarks on these:
- L74 + L75 : Make these variables not exported, use "trigger_in" / "trigger_out" as enums as advised by @dploeger 
- L76 @dploeger I did override get_class() initially, remember ? :)
