### ISSUE TITLE
Not handling characters without speech animation correctly

### ISSUE THREAD

**Issue by dploeger** [godot-escoria/escoria-issues#98]
**Please make sure you talk to the community before creating an issue.**

**Describe the bug**
In ESCItem#start_talking characters without speech animation aren't handled well. I think, that line 457 should rather be:

```animations.speaks.size() > 0:```

**Comment by balloonpopper** [comment]
@BHSDuncan I just refreshed my fork from the develop branch and when there's no ESCAnimationResource created for the ESCItem, a say command will cause the game to crash.
The error is "Invalid get index 'speaks' {on base: "Nil")

I would suggest inserting a not null check in addition to the size() > 0

**Comment by BHSDuncan** [comment]
Ugh, good catch. I had a fix for this already, but I pushed the wrong branch. Going to rectify that now.

**Comment by BHSDuncan** [comment]
Put up a quick PR. Just waiting for a review to merge.

**Comment by BHSDuncan** [comment]
Merged. Feel free to check now, and if you still don't see it, I'll proceed to pull out my hair and burn down GitHub. 👍
